### PR TITLE
Libreoffice folder renamed even when system requirement fails

### PR DESCRIPTION
**Pull request by Kassiematis**

### CODE REVIEW

**Comment by aalaesar** [comment]
@husisusi 
hi, sry but this one should not have been merged yet... 😕

**Comment by Kassiematis** [comment]
The script renames the libreoffice folder, before it checks the system requirements. If the requirements are not met the script stops. That leaves the server not functioning anymore without having to do repair- work.

**Comment by aalaesar** [comment]
I completely understand the issue, 👍 
But the PR breaks the logging and the purpose of this block initially : testing the host have enough disk space for when updating LO itself.
I'm reworking actually those points to avoid future failure.

**Comment by aalaesar** [comment]
PR #50 contains some fixes including 2 for this case.

**Pull request merged**
