### PR TITLE
Adds help text and make version configurable from commandline

### LINKED ISSUE #63: Pin versions
I tested the script and noticed it uses master on most of the versions. 

I want to build a server with a know-good-state and make it reproduce-able. AFAIK this is only possible, i need to edit "officeonlin-install.sh" and add the version numbers. 

Would it be a good idea to use parameter expansion for the version vars, like this:

http://stackoverflow.com/questions/4609668/override-variable-in-bash-script-from-command-line

That would make it possible to execute the script like this `lo_version=5.3.1.2 ./officeonlin-install.sh`

### PR DESCRIPTION
**Pull request by Gomez**
Fixes #63 

Needs some more testing. 

If it no param is given, everything works as before.

### CODE REVIEW

**Review by aalaesar — COMMENTED** [review]
Shouldn't be shift 2 because of the option's argument need to be consumed as well?

**Comment by Gomez** [comment]
What you mean?

**Comment by aalaesar** [comment]
oosp I missed the last shift after the case block,  sorry.
(I have tendency to wrap the shift in every case to isolate how each option behave from another.
so I missed the line after the `esac`!)
seems good 👍

**Comment by Gomez** [comment]
Cool! 
@husisusi You are able to merge? Right?

**Pull request merged**
