### PR TITLE
Install truetype msfonts

### PR DESCRIPTION
**Pull request by Kassiematis**

### CODE REVIEW

**Comment by aalaesar** [comment]
I'm ok with adding this but as optional ?
For this add non-free elements to the Software and some users may not want to use them.
Ex: Adding an option like `lo_non_free_ttf=false` (default) to choose to install or not those fonts.

**Comment by Kassiematis** [comment]
Sure why not. Can you add it to the script?

**Comment by Kassiematis** [comment]
@aalaesar 
I have made some changes to the patch, can you check it for me please?
https://github.com/husisusi/officeonlin-install.sh/pull/83/commits/f933281bb49880ee8cfa306cc66c3c4a1d2230a7

**Comment by aalaesar** [comment]
Sorry I can't test now, but it should work. 👍
You can also rely on apt-get being idempotent and use only 1 if block
This should do something like 
```shell
If ${lo_non_free_ttf}; then
  echo ...
  apt-get ...
fi
```
Regards.🙂

**Pull request closed without merging**
