### PR TITLE
officeonline-install2.sh

### PR DESCRIPTION
**Pull request by DmDS**
added officeonline-install2.sh. (and /bin/corePrep2.sh)

it uses [daily-built archive of LibreOffice core](https://github.com/CollaboraOnline/online/releases/download/for-code-assets/core-co-23.05-assets.tar.gz) (from [here](https://collaboraonline.github.io/post/build-code/#libreoffice-2)) instead of compiling LO from sources.
the script works much faster.

also added debian 12 support, latest openjdk for ubuntu and debian and other latest libs.

*and corrected config _(fatal: 'origin/distro/collabora/co-23.05$' is not a commit...)_ for compilation LO from sources with officeonline-install.sh

### CODE REVIEW

**Comment by husisusi** [comment]
Are you sure?
Are there any restrictions on this daily archive of core LibreOffice, max connections or max documents?
Okey, the restrictions are in lool dappled !
Hum..

**Comment by DmDS** [comment]
изображение
but this is only one user who has opened the same file 31 times.
let's ask someone to test officeonline-install2.sh) but I also think that all restrictions are specified in COOL.

**Comment by husisusi** [comment]
Agreed, let me check this installation.
Good job!

**Comment by DmDS** [comment]
some edits for Debian 12. now compiled successfully.

**Pull request merged**
