### PR TITLE
Support for Debian Stretch #79

### LINKED ISSUE #79: Debian 9
Hi, thanks for your work. 

Is there plan to support Debian 9 ?

Thanks.

### PR DESCRIPTION
**Pull request by embed-3d**
This should fix #79. It adds support for debian stretch.

### CODE REVIEW

**Comment by aalaesar** [comment]
Hi @embed-3d,
Thank you for the contribution. 👍
Did you tested the changes on Ubuntu LTS and debian 8 ? ☺️
Regards

**Comment by embed-3d** [comment]
Hi @aalaesar,
This needs to be tested.
Right now I found some problems related to my test setup!
Normally I do such testing/run my web servers in lxd/lxc containers. Due to some missing support of setcap in lxc, I'm not able run CODE in lxc/lxd. The loolwsd service run into errors, because of missing permissions.
I will start to test everything again with virtual box headless.
Regards

**Comment by embed-3d** [comment]
@aalaesar 
This comment will be updated during test procedure and should give an overview of the current testing state.
Right now all 3 VMs (debian stretch, debian jessie, ubuntu-16.04) are setup and running the script

debian stretch:
- [x] installation of packages was successful
- [x] compilation finished successful
- [x] admin interface is reachable and works
- [x] test document could be opened successful

debian jessie:
- [x] installation of packages was successful
- [x] compilation finished successful
- [x] admin interface is reachable and works
- [x] test document could be opened successful

ubuntu 16.04:
- [x] installation of packages was successful
- [x] compilation finished successful
- [x] admin interface is reachable and works
- [x] test document could be opened successful

After configuration:
-set backend password

Test url:
- https://admin:1234@serverip:9980/loleaflet/dist/admin/admin.html
- https://serverip:9980/loleaflet/1b5594f/loleaflet.html?file_path=file:///opt/online/test/data/hello-world.odt

**Comment by husisusi** [comment]
@embed-3d,
Thank you for the contribution!

**Pull request merged**
