### PR TITLE
Configure minimal build lio

### PR DESCRIPTION
**Pull request by sergey-dryabzhinsky**
- update apt-get packages
- use a lot of configure options to reduce build
- add debian/ubuntu special c/ld/flags extraction
- use sudo `-E` fag to preserve them

### CODE REVIEW

**Comment by sergey-dryabzhinsky** [comment]
Be aware of:
- --without-parallelism - build may be solwer. But cleaner.
- --disable-cve-tests - build faster. But no tests performed.

**Comment by husisusi** [comment]
Hi sergey-dryabzhinsky,
Than You! I will make some tests with your code.

**Comment by aalaesar** [comment]
Hi .
Why having it closed ?

**Comment by husisusi** [comment]
Sorry!

**Comment by husisusi** [comment]
On Debian 👎 , I did not test it on Ubuntu.
[build LNK] Library/libvcllo.so
/tmp/ccCIPM6w.ltrans16.ltrans.o: In function `HbLayoutEngine::Layout(ServerFontLayout&, ImplLayoutArgs&)':
ccCIPM6w.ltrans16.o:(.text+0x1b286): undefined reference to `hb_icu_script_to_script'
/tmp/ccCIPM6w.ltrans17.ltrans.o: In function `CommonSalLayout::LayoutText(ImplLayoutArgs&)':
ccCIPM6w.ltrans17.o:(.text+0x1898b): undefined reference to `hb_icu_script_to_script'
ccCIPM6w.ltrans17.o:(.text+0x18bf1): undefined reference to `hb_buffer_set_cluster_level'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/libreoffice/instdir/program/libvcllo.so] Error 1
/opt/libreoffice/vcl/Library_vcl.mk:20: recipe for target '/opt/libreoffice/instdir/program/libvcllo.so' failed
Makefile:263: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by sergey-dryabzhinsky** [comment]
What Debian version you're using?
Does packages from apt-get line all installed?
What files are downloaded to `/opt/libreoffice/external/tarballs/`?

**Comment by sergey-dryabzhinsky** [comment]
Did you upgraded libreoffice version?

**Comment by sergey-dryabzhinsky** [comment]
And did you run `make distclean` inside `/opt/libreoffice`?

**Comment by sergey-dryabzhinsky** [comment]
Found that `lsof` package needed to start `loolwsd` service.

**Comment by husisusi** [comment]
What Debian version you're using? Last 64 bit new fresh installed
Did you upgraded libreoffice version? No
Does packages from apt-get line all installed? Yes

**Pull request closed without merging**
