### PR TITLE
Missing packages debian 8

### PR DESCRIPTION
**Pull request by sergey-dryabzhinsky**
If Debian system installed in minimal version then apt may not install recommended or suggested packages.
So we must be sure that we install all of packages needed to build LiO.

### CODE REVIEW

**Comment by husisusi** [comment]
Thank you.
But 'openjdk-7-jdk' has no installation candidate in Ubuntu!

**Comment by aalaesar** [comment]
Hi @sergey-dryabzhinsky,
Are you working on building a loolwsd container ?

**Comment by sergey-dryabzhinsky** [comment]
@husisusi Uh, missed that.
Need to check distro (`lsb_release -sc`) and add to packages list appropriate pkg:
- openjdk-8-jdk - for Ubuntu 16.04
- openjdk-7-jdk - for Debian 8

**Comment by sergey-dryabzhinsky** [comment]
@aalaesar Yeap. Trying.

**Comment by husisusi** [comment]
we can use "shtool platform" to detect OS.

**Comment by sergey-dryabzhinsky** [comment]
@husisusi  I can't figure out how to make it output only distribution name.

**Comment by husisusi** [comment]
lsb_release is ok.

**Pull request merged**
