### PR TITLE
Compile of Loolwsd may be needed after installing mscorefonts

### PR DESCRIPTION
**Pull request by Kassiematis**

### CODE REVIEW

**Comment by aalaesar** [comment]
Need testing

**Comment by Kassiematis** [comment]
I tested it. With a compile of Libreoffice the fonts could not be used. After compiling Loolwsd the fonts could be used.
I first tested while compiling both that why I had Libreoffice instead of Loolwsd in my comment.
With a clean install it should be fine.

**Comment by aalaesar** [comment]
Hi.
In this case installing the package should set lo_forcebuild & lool_forcebuild to true but only if the package is installed on the run (aka test the pkg is installed before running apt install)

**Comment by Kassiematis** [comment]
Lool_forcebuild should be enough. But complicating the script with this just for some fonts? Anyone installing the fonts should set lool_forcebuild=true by themselves I should think.

**Comment by aalaesar** [comment]
That's what I first thought about this package. It could simply be installed before running the script 
But, hey why not.😊
However, you may want to fully integrate a feature when one is added. Unless you can handle to support requests or issues of users falling into half implemented use cases.😆

**Pull request merged**
